"""
chemical_component_sets_gen.jl — Generate chemical component set membership tables
from a CCD mmCIF file or from known-good hardcoded sets.

Usage:
  julia chemical_component_sets_gen.jl --ccd_mmcif /path/to/components.cif --output /path/to/sets.jl
"""

module ChemicalComponentSetsGen

using ArgParse
using Logging

"""
    classify_by_type(comp_type::String) -> Symbol

Classify a CCD component based on its _chem_comp.type field.
"""
function classify_by_type(comp_type::String)::Symbol
    t = uppercase(comp_type)
    contains(t, "PEPTIDE") && return :peptide
    contains(t, "RNA") && return :rna
    contains(t, "DNA") && return :dna
    contains(t, "SACCHARIDE") || contains(t, "SUGAR") && return :glycan
    t == "WATER" && return :water
    return :ligand
end

"""
    generate_sets_from_ccd(ccd_path::String) -> Dict{Symbol, Set{String}}

Scan the CCD mmCIF and classify each component into a category.
Returns a Dict mapping category name to Set of CCD codes.
"""
function generate_sets_from_ccd(ccd_path::String)::Dict{Symbol,Set{String}}
    @info "Scanning CCD from $ccd_path"
    sets = Dict{Symbol,Set{String}}(
        :peptide => Set{String}(),
        :rna     => Set{String}(),
        :dna     => Set{String}(),
        :glycan  => Set{String}(),
        :water   => Set{String}(),
        :ligand  => Set{String}(),
    )
    text = read(ccd_path, String)
    for block in split(text, r"\ndata_")
        m = match(r"^(\w+)", block)
        m === nothing && continue
        comp_id = m.captures[1]
        type_m = match(r"_chem_comp\.type\s+(\S+)", block)
        type_m === nothing && continue
        category = classify_by_type(type_m.captures[1])
        push!(sets[category], comp_id)
    end
    for (k, v) in sets
        @info "  $k: $(length(v)) components"
    end
    return sets
end

"""
    write_sets_julia(sets::Dict{Symbol,Set{String}}, output_path::String)

Write the generated sets as Julia source code constants.
"""
function write_sets_julia(sets::Dict{Symbol,Set{String}}, output_path::String)
    open(output_path, "w") do io
        println(io, "# Auto-generated by chemical_component_sets_gen.jl")
        println(io, "# Do not edit manually.")
        println(io)
        for (category, ids) in sort(collect(sets), by=x->string(x[1]))
            sorted_ids = sort(collect(ids))
            const_name = "CCD_$(uppercase(string(category)))_IDS"
            println(io, "const $const_name = Set{String}([")
            for chunk in Iterators.partition(sorted_ids, 10)
                println(io, "    ", join(map(id -> "\"$id\"", chunk), ", "), ",")
            end
            println(io, "])")
            println(io)
        end
    end
    @info "Wrote component sets to $output_path"
end

function main()
    s = ArgParseSettings(description="Generate CCD component set memberships")
    @add_arg_table! s begin
        "--ccd_mmcif"
            help = "Path to CCD mmCIF file"
            required = true
        "--output"
            help = "Output Julia file path"
            default = "component_sets_generated.jl"
    end
    args = parse_args(s)
    sets = generate_sets_from_ccd(args["ccd_mmcif"])
    write_sets_julia(sets, args["output"])
end

end # module ChemicalComponentSetsGen

if abspath(PROGRAM_FILE) == @__FILE__
    ChemicalComponentSetsGen.main()
end
